[package]
name = "divide-an-array-into-subarrays-with-minimum-cost-i"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
